Create Login endpoint & Signup Endpoint
mentorpaired/yaKitabuBackend pull request #30
Opened 2021-12-19 18:53 UTC by tosintubi

This PR fixes #17 and #16. 
It includes functionality for user login and signup endpoints as well as test cases covering them

2021-12-21 04:45 UTC, delphine-boke submitted a review, later dismissed
please separate the login and signup endpoints as one branch

2022-01-28 14:24 UTC, kosyfrances commented
@tosintubi is this ready for a review now?

2022-01-28 16:51 UTC, tosintubi commented
> 

@kosyfrances Yes, it is ready for review

2022-01-30 16:52 UTC, kosyfrances requested changes
Please rebase this branch properly as the seeder task should not be here as a new change.
I'll review when things are properly cleaned up.

2022-01-30 16:52 UTC, kosyfrances commented on README.md
> +  ```
I remember this is from a different PR. How is it magically here as a new change? 🤔
You probably need to rebase this branch properly.

2022-02-19 02:58 UTC, closed without merging